# Generated by Django 6.0 on 2025-12-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_edu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='student',
            name='studentNum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='教师ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='主机名'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherNum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='教师编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='年级'),
        ),
    ]
