# Generated by Django 6.0 on 2025-12-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_edu', '0003_alter_student_managers_alter_teacher_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentNum',
        ),
    ]
